lib: [
  "_build/install/default/lib/Game/META"
  "_build/install/default/lib/Game/board.ml"
  "_build/install/default/lib/Game/command.ml"
  "_build/install/default/lib/Game/controller.ml"
  "_build/install/default/lib/Game/dune-package"
  "_build/install/default/lib/Game/game.a"
  "_build/install/default/lib/Game/game.cma"
  "_build/install/default/lib/Game/game.cmi"
  "_build/install/default/lib/Game/game.cmt"
  "_build/install/default/lib/Game/game.cmx"
  "_build/install/default/lib/Game/game.cmxa"
  "_build/install/default/lib/Game/game.ml"
  "_build/install/default/lib/Game/game__Board.cmi"
  "_build/install/default/lib/Game/game__Board.cmt"
  "_build/install/default/lib/Game/game__Board.cmx"
  "_build/install/default/lib/Game/game__Command.cmi"
  "_build/install/default/lib/Game/game__Command.cmt"
  "_build/install/default/lib/Game/game__Command.cmx"
  "_build/install/default/lib/Game/game__Controller.cmi"
  "_build/install/default/lib/Game/game__Controller.cmt"
  "_build/install/default/lib/Game/game__Controller.cmx"
  "_build/install/default/lib/Game/opam"
]
libexec: [
  "_build/install/default/lib/Game/game.cmxs"
]
doc: [
  "_build/install/default/doc/Game/README.txt"
]
